config/routes.rb
Rails.application.routes.draw do
  resources :registers
  devise_for :users
  resources :events do
    resources :registers
  end
  root 'events#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
    belongs_to :user
    has_many :registers
end

app/models/register.rb
class Register < ActiveRecord::Base
    belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all.order('created_at DESC')
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @registration_count = @event.registers.count
    @registers = @event.registers
  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description)
    end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :set_register, only: [:show, :edit, :update, :destroy]

  # GET /registers
  # GET /registers.json
  def index
    @registers = Register.all
  end

  # GET /registers/1
  # GET /registers/1.json
  
  # GET /registers/new
  def new
    @register = Register.new
  end

  # GET /registers/1/edit
  def edit
  end

  # POST /registers
  # POST /registers.json
  def create
    @event = Event.find(params[:event_id])
    @register = @event.registers.new(register_params)

    respond_to do |format|
      if @register.save
        RegisterMailer.register_confirm_email(@register, @event).deliver
        format.html { redirect_to root_path, notice: 'Register was successfully created.' }
        format.json { render :show, status: :created, location: @register }
      else
        format.html { render :new }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registers/1
  # PATCH/PUT /registers/1.json
  def update
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to @register, notice: 'Register was successfully updated.' }
        format.json { render :show, status: :ok, location: @register }
      else
        format.html { render :edit }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registers/1
  # DELETE /registers/1.json
  def destroy
    @register.destroy
    respond_to do |format|
      format.html { redirect_to registers_url, notice: 'Register was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register
      @register = Register.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def register_params
      params.require(:register).permit(:name, :branch, :semester, :event_id, :email, :mobile_no)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %> <br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %> <br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<% @events.each do |event| %>
  <div class="event row clearfix">
    <h2>
      <%= link_to event.title, event %> <br>
      <small class="author">
        Submitted <%= time_ago_in_words(event.created_at) %> ago by <%= event.user.email %>
      </small>
    </h2>
  </div>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="page-header">
	<h1>
		<%= @event.title %> <br>
		<small>Submitted by <%= @event.user.email %></small>
	</h1>
</div>

<p>
  <%= @event.description %>
</p>



<% if @event.user == current_user %>
  <div class="btn-group">
  	<%= link_to "Edit", edit_event_path(@event), class: "btn btn-default" %>
  	<%= link_to "Destroy", @event, :method => :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>  
  </div>
  
  <p>
    <%= @registration_count %> candidates have registered for this event.
  </p>
  
  <table>
    <tr>
      <th>Serial Number</th>
      <th>Registeration ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>Branch</th>
      <th>Semester</th>
      <th>Mobile Number</th>
    </tr>
    <% @count = 0%>
    <% @registers.each do |register|  %>
      <tr>
        <% @count = @count + 1 %>
        <td><%= @count %></td>
        <td><%= register.id %></td>
        <td><%= register.name %></td>
        <td><%= register.email %></td>
        <td><%= register.branch %></td>
        <td><%= register.semester %></td>
        <td><%= register.mobile_no %></td>
      </tr>
    <% end %>
  </table>
  
<% else %>
  <%= simple_form_for [@event, Register.new]  do |f| %>
    <div class="field">
      <%= f.input :name, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.input :branch, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.input :semester, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.input :email, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.input :mobile_no, class: "form-control" %>
    </div>
    <br>
    <%= f.submit "Register", class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Registration Hub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-default" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        
        <div class="navbar-brand" id="logo">
          <%= link_to "Registration Hub", root_path %>
        </div>
        
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
          <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Create Event", new_event_path %></li>
              <li><%= link_to "Account", edit_user_registration_path %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
            </ul>
            <% else %>
            <ul class="nav navbar-nav pull-right">
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Sign in", new_user_session_path %></li>
            </ul>
          <% end %>
        </nav>
      </div>
    </div>
  </header>

  <div id="main_content" class="container">
    
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    <div id="content" class="col-md-9 center-block">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/registers/_form.html.erb
<%= form_for(@register) do |f| %>
  <% if @register.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@register.errors.count, "error") %> prohibited this register from being saved:</h2>

      <ul>
      <% @register.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :branch %><br>
    <%= f.text_field :branch %>
  </div>
  <div class="field">
    <%= f.label :semester %><br>
    <%= f.number_field :semester %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.number_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/registers/edit.html.erb
<h1>Editing Register</h1>

<%= render 'form' %>

<%= link_to 'Show', @register %> |
<%= link_to 'Back', registers_path %>

app/views/registers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Registers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Branch</th>
      <th>Semester</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registers.each do |register| %>
      <tr>
        <td><%= register.name %></td>
        <td><%= register.branch %></td>
        <td><%= register.semester %></td>
        <td><%= register.event_id %></td>
        <td><%= link_to 'Show', register %></td>
        <td><%= link_to 'Edit', edit_register_path(register) %></td>
        <td><%= link_to 'Destroy', register, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Register', new_register_path %>

app/views/registers/new.html.erb
<h1>New Register</h1>

<%= render 'form' %>

<%= link_to 'Back', registers_path %>